### ISSUE TITLE
Version number inconsistency

### ISSUE THREAD

**Issue by dchekanov** [SevaSafris/cordova-plugin-statusbar-hide-on-startup#2]
`package.json` says the version is 0.1.0, and `plugin.xml` says it's 0.1.2. This causes an issue: when you add a plugin with the `--save` flag, it writes 0.1.2 to `config.xml`, and when you clean up and rebuild the project based on the `config.xml` info, it fails because only 0.1.0 is available on npm.

Please update versions to match (probably by bumping npm version string and publishing it).

**Comment by SevaSafris** [comment]
Thank you for sending me a note about this. I've updated to v0.1.4. Please let me know if there's anything else I missed.

**Comment by dchekanov** [comment]
Thanks for responding so quickly. Unfortunately, the package you published on npm still has mismatching versions: 0.1.4 in the `package.json` and 0.1.2 in the `config.xml`.

**Comment by SevaSafris** [comment]
How do I change that? I can't find a mention of 0.1.2 any more.

**Comment by dchekanov** [comment]
It is likely that you've published the package to npm after changing version to 0.1.4 in the `package.json`, but before adjusting the version in the `plugin.xml` (sorry, I wrote "config.xml" by mistake in the previous comment). 

You can verify version mismatch by running `npm i cordova-plugin-statusbar-hide-on-startup` and checking `node_modules/cordova-plugin-statusbar-hide-on-startup/plugin.xml` contents. It will read "0.1.2". Or download and unpack the package manually from https://registry.npmjs.org/cordova-plugin-statusbar-hide-on-startup/-/cordova-plugin-statusbar-hide-on-startup-0.1.4.tgz.

To fix the issue, make sure you have identical versions in both `plugin.xml` and `package.json` and only then publish the package.

**Comment by SevaSafris** [comment]
Okay! I think I got it right this time -- version 0.1.6 now. Thank you for the guidance. What an unfortunate design.

**Comment by dchekanov** [comment]
The issue is solved now, thanks!
